#!/bin/bash

. developers.list

header="#
# DO NOT EDIT THIS FILE
#
# It is automatically generated by script
#

"

cd list
f=`find . -name "gitlog*$1.list"`

for fp in $f ; do
  unset list
  declare -A list
  
  lang=$fp
  lang=${lang#*_}
  lang=${lang%.list}
  outfp=${fp/gitlog/translators}
  outfp=${outfp%list}info
  echo -n "$outfp "
  IFS=$'\n'
  lines=`cat $fp`
  for line in $lines; do
    case ${line:0:1} in
      "F")
        filename=${line#??}
        echo -n "."
        ;;
      "A")
        author=${line#??}
        dev=false
        let count=0
        langs=${developers[${author##* }]}
        if [[ -n $langs ]] ; then
          if ! [[ $langs =~ .*$lang.* ]] ; then
            dev=true
          fi
        fi
        if [[ "yast4ik@yahoo.com" == ${author##* } ]] ; then
          echo -n "Y"
        fi
        ;;
      " ")
        if ! $dev && (( $count > 0 )) ; then
          let list["$author"]=list["$author"]+count
        fi
        ;;
      [0-9])
        if [[ $line =~ .*/[^_]*_(.*).ts ]] ; then
          la1=${BASH_REMATCH[1]}
          la2=$lang
          if [[ ${la1:0:2} != ${la2:0:2} ]] ; then
            dev=true
          fi
        elif ! [[ $line =~ .*(.desktop.in|.desktop|.ts) ]] ; then
          dev=true
        fi
        if [[ $line =~ .*$filename ]] ; then
          let count=count+${line%%$'\t'*}
        fi
        ;;
    esac
  done
  
  unset IFS
  all=$(
    for author in "${!list[@]}"; do
      echo ${list[$author]} $author
    done | sort -k2 -f  # sort by Author
    #done | sort -nr     # sort by Count
  )
  
  IFS=$'\n'
  num=1
  oneline=""
  info=""
  for line in $all; do
    count=${line%% *}
    author=${line#* }
    author=${author% *}
    mail=${line##* }
    if [[ ${mail#*@} == "users.noreply.github.com" ]]; then
      mail=${mail%@*}
      mail=https://github.com/${mail#*+}
    fi
    printf -v str "%5d %-40s" $count "<$mail>"
    oneline=$oneline"#[$lang] $str $author"$'\n'
    info=$info"
translator_${num}_nameEnglish = $author
translator_${num}_contact = $mail
"
    let num++
  done
  if [[ -z $info ]] ; then
    echo -n "R"
    rm -f $outfp
  else
    echo "$header$oneline$info" > $outfp
  fi
  echo
done
